---
exclude_paths:
  - "src/views/incidents-view.test.ts"
  - "src/views/reports-view.test.tsx"
  # Codacy is running a T-SQL linter over our SQLite migrations; exclude them to
  # avoid false positives.
  - "src-tauri/src/db/sql/*"
