---
exclude_paths:
  - "src/views/incidents-view.test.ts"
  - "src/views/reports-view.test.tsx"
  # Current Codacy analyzers misinterpret parts of our TS/TSX and flag false
  # positives on modern syntax; keep these excluded until the Codacy config is
  # aligned with our TypeScript toolchain.
  - "src/hooks/use-pir-review.ts"
  - "src/views/learnings-view.tsx"
  # Codacy is running a T-SQL linter over our SQLite migrations; exclude them to
  # avoid false positives.
  - "src-tauri/src/db/sql/*"
